language: node_js
node_js:
- node
services:
- docker
addons:
  apt:
    packages:
    - ruby-full
before_install:
- docker pull mongo
branches:
  only:
    - master
    - release_2

install: npm install
script: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: dndGBLPAZoUQl7qZXXr5E81rFy24eH0i3u0KaXLWZ9O7rQAlqud27oIoD1/4Vm7XpwZrWdKRQM2S3YXhb2ciyx8LeTczbIq6Yl+aF3rNw6ZEE5XRugSdRyRvtLCzTpC4MCPaLj0QIZF0ohaVBkVFkcGcDHpdviKaoLHvgeWARki6Y84VS6qKsZeDDQkAz4Rh6nXJxuhlGvPUZ5yikGZkUqUwJ9n0YPEVaZoojF9Br+lsu2DsYyhiCcxrv143kK/ZlrZM4WwFiBphnwyjnPNEpS3yf0jcNp2DMWlXm9YhhKW1xa4o1yrzrm0jQhi7t2Ab485+PxzzH/yYbedXrsqBuqtbPRgXRzndxM34RjUX9eY9P5XDeshHw4uwGi3+YnvktzL4W8tI5AWdz7+XP/iIqNUML/I5hNW8Igy73PXcGLqoLYicjnthJSFmGxZ9XDT6OdM06mJpBWtHXoa2vB+Wtef8pJyRLBsVf7bZ11/B5djwhfVgY8SGvWnFqXCxmflWiTtiSENyK3q52SSbMuE2oxiAqObXxShGgmjSFSYGRxsgh7KKJVtvKIFk+rKj+/LToWiRkI3ziUldVcLqZrOB+6LFh4xMmJlF1ONP3UFqOTFAy3gJOGEsC8i7kpN5Kbn15MATSFuOaNFnvqZsw/IPR6675tQHTqyDBm+StuTzWg4=
  app: tranquil-dusk-38037
notifications:
  email: false
  slack:
    rooms:
    - csce431workspace:1BaoZx9I1S5rPmey5C1skttX
    on_success: always
    on_failure: always
env:
  matrix:
  - secure: mEQG8Ug5j9tatjDxM+k+xkZAgiezuKmQc/LM1X24ZazrtrXJY+JS4IBD1eHIMYky9u9YqYabfUDZbVLC/bgyGiFLJxjUc4DZuLKPj6SXSNdFKlcyexkZBJ1WiJIN1HbdOQEtgtAsI+okOP4C5DLdWbyBc2cQsPjII0F4QK8vWDrIlSvXOH60hUSO+wDjfeYs1h5vQrh/OXSxpP2ExGRDjBlszrXPEKQgil3kDCaWplIFLRD733ANEGyoVDzYEa/J6XxMdxK64t0ZD34sQXAMd6gMvT8rOBOBeq3K1LFD2ohUFpIKmmqMbVp4tBEv0NylML+xFoq2yXOOzKHfEZGcHL8THrjFw/I77hGLjl/ifHLMyuOFPOwl2iz9OB3CPTBOfEVxQLsNbJZVmBFXnwpbHWBSyGoKf4NEIPkPDUrlxRAPPfAMa/BZtw3INMKvD+P/59jCDGhnC6G9Y3lKfO4o5GhH5QUjZ6AGYIzHhHJMkbfQmsxmRO0XPDZcFtRc6Y39P+ace/IHrheEn+3CNXlItgQs3YNKfRRbeYC734G8UuotlePGBjcYgJ+PzqXtt4fit8pGVbxWts27hwIWVH0wzmRA4V8Kp3SGEm1TEJU1V/1Hb6GxIeU5Cs9/Dl5QSFVPJdiNuWXA4i5mVgzNoTX4hG7P8nicAk3sOhQkU3QBLPA=
  - secure: hkyHEB61yhR+WHDxB8xXhpvtQ3XBTzVS0La/6XXH/x2Alq8xJH/Noweo0iawTGZQd3ywbG7Y50DQUQiZU2W0uvdkTLpLV+lFMAWpfiagxnDMkLkYX8QpnLx0M9nQ+JJPKwhMnAK4G9yrMNpcjxtGe8YhzP8HwkBIed0aubcEEX/K2WeFtALsGVYzEO0X65uRjGCvR8+SgmsCSnTTD8JLs6vzag0zuSZDApqBZz6efUBgHw3hxqMhN7fljx4YlkMdT7ooIYARLyMEWr+MfhkKN1vhACftIe2XsE3ikK5N0g6LmKo0rFRi9ylJr48WXNDbr85sdT9QkxIHi/XKnd3PLxLSADCiInqXO4rhc3HyGxBZRNnPDGfrVM36BjyPMZslYrFdEUYrXpVCeX0/VnnngmThTFRoBqW1JvvCnJb2T/6nqzX2bPKlDjiKHK8HREudrAgviSpBAeLaITG2aobKi4Hb4f1xZadDrnkhSxovD3QxFTTXuiJVZicpEaA26yIWSOoQXwG9e4U8GZfGNvxpFsD7DXv87q3SaNsAnlpPUFq8TVkKkcQ+Ior2nom5zbIv0cKAKbU45Jko09XnKKoFidsfkPd3Rm7kfVpV52RQA4cF7+5BFGjMlnpADZomSMKpAY6OsYmJ7E6lkoWPaA7SJWhM/byt7lOkLMVqRBC4lKc=
  - secure: pa1g9Z93R0WwqfQW6emsRCwudHyL0AeAFG7ftJ9ZJf5vmryv+Hpncz283gcmQ5PPrdG7FBZ6RtIBh4HF2i5W+1vpHKkgN6PEACYaaml5995XDhuUYqr1hIVqInuSywCIifnSiZ9KjKsFn78Z5KXSBHJ16Zf+BfcfoZvViJ4FcsRN9zVpUnF3NbmEnxGA7Gir31qpq7RYH/rGjDi7HsNyuV+06IWpHOBOyY4iPnxecic3xP7r2AgjES8pWRKPBNju76eJaOWGrLuwEtE62W6MBjkwcCRL2Y1vKdJ2U/G7VK8DLt2cZV+NU571kLvPwr7g1JTcTQKsgcp57QaPxagnlKpujgGARA37satcp4AsWXUqtvGfl9kRjDZLt7O4zyyNUA07DmwBzG18rw/4ut2eIMbvUhSDTOwQjHdID9c9DqaisIDPCDg1lZVcNkDqYoZNCpytDXUdFVEcEkGRUeWsK7Yqy8+p8AiAz7HKSZhTYOGWUiK8wtOOoi98WPebezwxn2Wtg+cOQLN4bEtEjkfR6uD6VkMS9MgiFKLN4WNW+Y/OwyXoj8mmePyiQcJufebcgmNh3RlynuXKH19CF1hrMlnsJ/YsU6A7+dZ+Z5dP9Xp9Ts/p4Z/o5USEJ2EWudMYDGgQPaYBFMxOFvuZDzqNK8ptKFf6iRT4FiqMPXodViU=
