language: node_js
node_js:
  - "node"

services:
  - docker

addons:
  apt: 
    packages:
    - ruby-full

before_install:
  - docker pull mongo

branches:
  only:
    - master
    - release_2

install: npm install

script: npm run coverage

deploy:
  provider: heroku
  api_key:
    secure: "dndGBLPAZoUQl7qZXXr5E81rFy24eH0i3u0KaXLWZ9O7rQAlqud27oIoD1/4Vm7XpwZrWdKRQM2S3YXhb2ciyx8LeTczbIq6Yl+aF3rNw6ZEE5XRugSdRyRvtLCzTpC4MCPaLj0QIZF0ohaVBkVFkcGcDHpdviKaoLHvgeWARki6Y84VS6qKsZeDDQkAz4Rh6nXJxuhlGvPUZ5yikGZkUqUwJ9n0YPEVaZoojF9Br+lsu2DsYyhiCcxrv143kK/ZlrZM4WwFiBphnwyjnPNEpS3yf0jcNp2DMWlXm9YhhKW1xa4o1yrzrm0jQhi7t2Ab485+PxzzH/yYbedXrsqBuqtbPRgXRzndxM34RjUX9eY9P5XDeshHw4uwGi3+YnvktzL4W8tI5AWdz7+XP/iIqNUML/I5hNW8Igy73PXcGLqoLYicjnthJSFmGxZ9XDT6OdM06mJpBWtHXoa2vB+Wtef8pJyRLBsVf7bZ11/B5djwhfVgY8SGvWnFqXCxmflWiTtiSENyK3q52SSbMuE2oxiAqObXxShGgmjSFSYGRxsgh7KKJVtvKIFk+rKj+/LToWiRkI3ziUldVcLqZrOB+6LFh4xMmJlF1ONP3UFqOTFAy3gJOGEsC8i7kpN5Kbn15MATSFuOaNFnvqZsw/IPR6675tQHTqyDBm+StuTzWg4="
  app: tranquil-dusk-38037

notifications:
  email: false
  slack: 
    rooms:
      - csce431workspace:1BaoZx9I1S5rPmey5C1skttX
    on_success: always
    on_failure: always

env:
  global:
    - secure: tp3OM+eViSVqlQ2UUgObvu6pFQeL6Ivmrjat0nxVNLtStAc27IC1tjFAcwOb1KYCv/U9LJ4vUBuzqob2c9UH05EUb8OlhLoMA1Kg2fx3uF8Mt6pS27ST0pD9kAMcIladCFlnwS6NcjJN6EuS+fYaCYiTKbe/nmHh46ptUVnp92PnX2tHJEcxtaOGIlMuoxBRMf/A4vgx0ymmXahjSSWoWbk6rQOMft1rwBnxodXTMt+py6p1QORs6GOXI8Qgux36aBUORnwRbAZICyf9cIdliSed2rSKbc+4OZFF1IeswonT5ShZTxq2M6ejU0Bjgi28708UZ3wZi0z2f4ze9MyK7PIexQVU3ECvHDo6j9bmeSB+NVGmqiAu8bdXvGxyU8sSrFIUsXS3mXiw29eW2VA0vZuf0NiGYUWS+wuwldcfxgB18mpG+u6TZDtzVlT4eFCGFzcWgwdlU8fhi0srh6175PrGYsc3zr1ir+jX0/RRpKqCLSeFNeph6LBruIRvNbcuF1Bu1ZEd12zJP7ywBokcCa0u8kcEsgAtbAXnwgDCOfFekOGUWhb4AfJ+vTg/1WsInA33OOe/KnV/ttfqeEuJKOxqvFkSiCbMyhWmxme7Xeap3i2ucP0B8GxSiSo08zL9Sfbx1HcF6C7UX+/v4Icv0hJVUDqW7l0BZIELB8e3PLo=
    - secure: OhSAvqejYThZ8FvdhBR8lIrneckJHw4AzGNhBf79ka3ptjr9PufE4b7TTE2UXHr+Gq9oH+2TmRI8Ar58eywYwclb/AN/n5eCDnSZzwcX2Q9wWUeJh3MoNM+mjoXWLOkbN4FbsPEz82K/NUpJ/eJWpO/JgYHE8c+k6zPg4XHNJKa+o93T9UG0ICxOxpXBF8KUaJqmuO5cjAJP7JP6Mi6ww2YyT50f8v4aCMwlWoFeihUvP4zPqYRDYs5zW7hw/EyYjOQhUPH3tQjppaM71sqXr+H+p+ZnxHHlbI2LBZWkZgi+FhhWQyuChOpVHfpjK/3Q4OyGWSOE0wBDQK9FxMbs0LRdYWQLK0Zl1/Dp6Bni98oq7q1tmu+P9fdu9Z+oj8uZhwTcJzcP3DTNkA3+9DaTgRdJcgNls1f+NEnx2WQ2Pug/2UBBd8PzQcRRRCZli+GlGB8Z+LHaNWj3t3Q1xxuz7y9VI9eZQ9Cip1odN1qW8gFlWxeNMo3MgDerJBldMHBQvj7SBwKGLloARuMwEnkKT2M/AI/GbCT0rBmOctQWl7J+ZYw0+qb17NjNtRQLlX69zgGMZrXIMm+7E0yE4FjOdHhl7LlLU2uSyWFnBD29MvR+NBLE3BHo34dkmnLXSPazox+T2UmOrrhnjJ6Qje2xyuVBsFNCadQaN4n9wxrggkY=
    - secure: Ilgw2at1W3l/mOTr2gykojmekMTkVBKymufNkKMmJdnf12HHUMRTAkPyD7q6d6xXeUBZfpB/POQXhFpsB+LIA0LEbECNPt9klPTAxjgG0z371nzWnObi3blGwZa1Z/UQF7SEnRuSKj+9nbnbwHzPKu0DEdKgdbGUGZaYZ3c+2G/2ITLbuK3kumZhTod3h3rVmBZkYJxtVBXZmR56U18VgymREBIKjuSaH6HBpZJbz5bGHCJW++3Go9AYDvA9hjzL3i/CQ2aVF30GOnebuY/LDdiw0zjuQ00siGaxq2puNBjVHH4trD88OdfnH5Fjmw4X7OKYOUek9jgM45UjSamnH5glTSVBAHzJ0svoaLqnXd9UnOCe5BMTJA1wq+AMHgU2thg0k/ex2N0EuQJlF1WvLUH71NFxrVrh0OhqrfCVdknG8vl3sOl1RVuAnwV4Q9PerkHGY0baaRG6MP4IQ7w7C+iETzlC99TabI2U0oBAud3LdRwFDG7r3FotxRi68eRhyzfthfSSCxrAvI8mbvjoS0clXBR18zv5wLt7EHMIH2TwsoQpvyd3eOPZPWJuxWf5p9wE/wzNv2CYHS2mJBapUQlNhKti200e90hEyZpK3mA/x/zskq8uez1aWvdvQLfTblQ6hKv885kyxv4BAWawT0PeXZ8YdHa5NJ/PkOhzRi8=