language: node_js

addons:
  apt: 
    packages:
    - ruby-full

install: npm install

script: npm test

deploy:
  provider: heroku
  api_key:
    secure: "dndGBLPAZoUQl7qZXXr5E81rFy24eH0i3u0KaXLWZ9O7rQAlqud27oIoD1/4Vm7XpwZrWdKRQM2S3YXhb2ciyx8LeTczbIq6Yl+aF3rNw6ZEE5XRugSdRyRvtLCzTpC4MCPaLj0QIZF0ohaVBkVFkcGcDHpdviKaoLHvgeWARki6Y84VS6qKsZeDDQkAz4Rh6nXJxuhlGvPUZ5yikGZkUqUwJ9n0YPEVaZoojF9Br+lsu2DsYyhiCcxrv143kK/ZlrZM4WwFiBphnwyjnPNEpS3yf0jcNp2DMWlXm9YhhKW1xa4o1yrzrm0jQhi7t2Ab485+PxzzH/yYbedXrsqBuqtbPRgXRzndxM34RjUX9eY9P5XDeshHw4uwGi3+YnvktzL4W8tI5AWdz7+XP/iIqNUML/I5hNW8Igy73PXcGLqoLYicjnthJSFmGxZ9XDT6OdM06mJpBWtHXoa2vB+Wtef8pJyRLBsVf7bZ11/B5djwhfVgY8SGvWnFqXCxmflWiTtiSENyK3q52SSbMuE2oxiAqObXxShGgmjSFSYGRxsgh7KKJVtvKIFk+rKj+/LToWiRkI3ziUldVcLqZrOB+6LFh4xMmJlF1ONP3UFqOTFAy3gJOGEsC8i7kpN5Kbn15MATSFuOaNFnvqZsw/IPR6675tQHTqyDBm+StuTzWg4="
  run: "npm run prod"

notifications:
  email: false
  slack: 
    rooms:
      - csce431workspace:1BaoZx9I1S5rPmey5C1skttX
    on_success: always
    on_failure: always